### ISSUE TITLE
EMC / ECS integration

### ISSUE THREAD

**Issue by ligerard** [cermegno/Project-Vision#1]
Hello,
Have you plan to include support for ECS ?

**Comment by cermegno** [comment]
Hi ligerard, I have discussed this with a colleague that works with ECS and he is working on this at the moment. He is focusing on 2 areas: S3 object management and on array management. He is hoping to have it ready by the end of October. We will publish his collection here. Thanks

**Comment by ligerard** [comment]
Hi cermegno
Thanks for your answer.

**Comment by cermegno** [comment]
> Hi cermegno
> Thanks for your answer.

Hi ligerard, my colleague has now finished the two collections for ECS management and the S3 API. We have posted the collection files here. I have also added a link in the ReadMe to a repo he has created with more details such as environment requirements. We hope it helps
